version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "backdb"
      POSTGRES_USER: "backUser"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5432:5432"